import type { NextPage } from 'next'
import { useRouter } from 'next/router'
import Head from 'next/head'
import styles from './Home.module.css'

const Home: NextPage = () => {
  const router = useRouter()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className="spinner-border" role="status">
          <span className="visually-hidden">Loading...</span>
        </div>

        <button
          type="button"
          className="mt-5 btn btn-dark btn-lg"
          onClick={() => {router.push("/sample-page")}}
        >
          Go To Sample Page
        </button>
      </main>

    </div>
  )
}

export default Home
